[package]
name = "row_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bootloader = { version = "0.9.23", features = ["map_physical_memory"]}
linked_list_allocator = "0.10.5"
pc-keyboard = "0.7.0"
pic8259 = "0.10.4"
spin = "0.9.8"
x86_64 = "0.14.10"


[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
